---
- apt_repository: repo=ppa:openjdk-r/ppa update_cache=yes

- apt: pkg="{{ item }}" state=latest update_cache=yes cache_valid_time=3600
  with_items:
    - openjdk-{{ openjdk_version }}-jdk
    - git
    - unzip
    - python-pip

- pip: name=docker-py version=1.9.0 umask=0022

- name: set time zone
  copy: content={{ time_zone }} dest=/etc/timezone mode=0644 backup=yes
  notify: update time zone
  when: system_time_zone != time_zone