# -*- mode: ruby -*-
# vi: set ft=ruby :

# initialize home folders
vagrant_home='/home/vagrant'

guest = {
  workspace_home: "#{vagrant_home}/workspace",
  sdk_home: "#{vagrant_home}/sdk",
  configuration_home: "#{vagrant_home}/configuration",
  data_home: "#{vagrant_home}/data"

}

host = {
  workspace_home: '../workspace',
  sdk_home: '../sdk'
}

Vagrant.configure("2") do |config|
  config.vm.box = 'ubuntu/trusty64'

  config.vm.provider "virtualbox" do |virtualbox|
    virtualbox.memory = 4096
  end

  # forwarded ports
  config.vm.network 'forwarded_port', guest: 8080, host: 8080, auto_correct: true
  config.vm.network 'forwarded_port', guest: 3306, host: 3306, auto_correct: true
  config.vm.network 'forwarded_port', guest: 6379, host: 6379, auto_correct: true

  # synced folders
  config.vm.synced_folder host[:workspace_home], guest[:workspace_home], owner: 'vagrant', group: 'vagrant'
  config.vm.synced_folder host[:sdk_home], guest[:sdk_home], owner: 'vagrant', group: 'vagrant', create: true

  config.vm.provision "docker"

  config.vm.provision 'ansible', run: "always", type: 'ansible_local' do |ansible|
    ansible.sudo = true
    ansible.verbose = true
    ansible.playbook = './playbook.yml'
    ansible.extra_vars = {
      application_name: 'my_app',
      timezone: 'Asia/Singapore',

      vagrant_home: vagrant_home,
      workspace_home: guest[:workspace_home],
      sdk_home: guest[:sdk_home],
      configuration_home: guest[:configuration_home],
      data_home: guest[:data_home]
    }
  end
end