jetpacker:
  openjdk: [ 7, 8 ]

  nvm:
    name: nvm
    namespace: creationix
    endpoint: GitHub
    description: Node Version Manager - Simple bash script to manage multiple active node.js versions.

  node:
    name: node
    namespace: nodejs
    endpoint: GitHub
    description: Node.js is a JavaScript runtime built on Chrome's V8 JavaScript engine. Node.js uses an event-driven, non-blocking I/O model that makes it lightweight and efficient. Node.js' package ecosystem, npm, is the largest ecosystem of open source libraries in the world.

  guard:
    name: ruby
    namespace: ruby
    endpoint: GitHub
    description: Guard is a command line tool to easily handle events on file system modifications.

  boxes:
    - name: ubuntu
      description: Ubuntu is an open source software platform that runs from the cloud, to the smartphone, to all your things.
      images:
        - ubuntu/trusty32
        - ubuntu/trusty64
      defaultImage: ubuntu/trusty64

  databases:
    - name: mysql
      description: MySQL is the most popular Open Source SQL database management system.
      endpoint: DockerHub

    - name: mariadb
      description: MariaDB is an enhanced, drop-in replacement for MySQL.
      endpoint: DockerHub

    - name: postgres
      endpoint: DockerHub
      description: PostgreSQL is a powerful, open source object-relational database system.

    - name: mongo
      endpoint: DockerHub
      description: MongoDB is an open-source, document database designed for ease of development and scaling.

    - name: redis
      endpoint: DockerHub
      description: Redis is an open source (BSD licensed), in-memory data structure store, used as database, cache and message broker.

  messageQueues:
    - name: rabbitmq
      endpoint: DockerHub
      description: RabbitMQ is a lightweight, reliable, scalable and portable message broker.

  searchEngines:
    - name: elasticsearch
      endpoint: DockerHub
      description: Elasticsearch is a distributed, open source search and analytics engine, designed for horizontal scalability, reliability, and easy management.

    - name: solr
      endpoint: DockerHub
      description: Solr is the popular, blazing-fast, open source enterprise search platform built on Apache Lucene.