jetpacker:
  boxes:
    - name: ubuntu
      description: Ubuntu Linux OS
      defaultImage: trusty64
      images:
        - precise32
        - precise64
        - trusty32
        - trusty64